services:
- docker
script:
  # Build
  - docker build --target test --tag todo-app:test .

  #Tests
  #Unit & Integration tests
  - docker run todo-app:test tests

  # End to End test
  - docker run -e SECRET_KEY -e TOKEN todo-app:test tests_e2e

before_deploy:
- echo $docker_hub_password | docker login --username $docker_hub_username --password-stdin
- docker build --target production --tag sjain309/todo-app-prod:latest .
- docker push sjain309/todo-app-prod:latest
# test

notification
  slack: amex-corndel-devops:aP3GLzh4WeVyZsfQSAAKEAVC
  email:
    recipients:
      - sushma.crawley@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
