# Copy this into a file called `docker-compose.yml`
version: "3.2"

services:
  todo_app_prod:
    container_name: production
    image: todo-app:prod
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: ./todo_app
        target: /todo_app/todo_app
    ports:
        - 5000:5000
    env_file:
        - .env

  todo_app_dev:
    container_name: Development
    image: todo-app:dev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: ./todo_app
        target: /todo_app/todo_app
    ports:
      - 5001:5000
    env_file:
      - .env
      
  todo_app_test:
    container_name: tests
    image: todo-app:test
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: ./tests
        target: /todo_app/tests
        env_file:
          - .env.test
      
  todo_app_test_e2e:
    container_name: test_e2e
    image: todo-app:test
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - type: volume
        source: ./tests_e2e
        target: /todo_app/tests_e2e
        env_file:
          - .env
  
